/*
ckomputer - Vulkan C wrapper library that provides compute functionality
Copyright (C) 2025  Andrew Hall

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

License location: <project-root>/COPYING
Contact e-mail: camo5hark10@gmail.com
Git repo: https://github.com/Camo5hark/ckomputer
 */

#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0) uniform in_multiplier {
    float in_multiplier_val;
};
layout(std430, binding = 1) readonly buffer in_numbers {
    float in_numbers_data[];
};
layout(std430, binding = 2) buffer out_numbers {
    float out_numbers_data[];
};

void main(void) {
    uint index = gl_GlobalInvocationID.x;
    out_numbers_data[index] = in_numbers_data[index] * in_multiplier_val;
}
